### ISSUE TITLE
New version of the CPPAN client is available!

### ISSUE THREAD

**Issue by zdenop** [cppan/cppan#10]
I downloaded client from: https://cppan.org/client/cppan-master-Windows-client.zip
When I run `cppan` I got this message:
```
New version of the CPPAN client is available!
Feel free to upgrade it from website or simply run:
cppan --self-upgrade
(or the same command but from administrator)
```

So I run cppan --self-upgrade with this result:
```
New version of the CPPAN client is available!
Feel free to upgrade it from website or simply run:
cppan --self-upgrade
(or the same command but from administrator)

Downloading checksum file
Downloading the latest client
Unpacking
Replacing client
```

When I run  `cppan` once again I got message that new version is available and I should....

**Comment by egorpugin** [comment]
Hmm. Is this message still visible in 1 hour? 3 hours? 24 hours?
There's possibility that's something wrong with TZ handling.

**Comment by zdenop** [comment]
Yes, I still get the same message  several hours.
I tried to remove  .cppan directory but it does not helped.

**Comment by egorpugin** [comment]
Please, update the client one more time (any way - from site or via command). And then try to see if problem persists.
I've uploaded the new client, but cannot say for sure whether it's fixed.

**Comment by zdenop** [comment]
I  tried both way for upgrade, but no change. 
`cppan --version` produces:
```
New version of the CPPAN client is available!
Feel free to upgrade it from website or simply run:
cppan --self-upgrade
(or the same command but from administrator)

cppan version 0.2.0
assembled 2016-12-30 23:39:08
```

**Comment by egorpugin** [comment]
Please, check again (via `--self-upgrade`). New `--version` shold say 7 Jan and `0.2.1` version.

**Comment by zdenop** [comment]
Thanks. This issue is fixed.
