### ISSUE TITLE
Package 'pvt.cppan.demo.leptonica' not found.

### ISSUE THREAD

**Issue by zdenop** [cppan/cppan#11]
I am not sure if this is cppan issue or tesseract, but when I run `cppan` I got message:
```
Downloading database
Cannot get dependencies from local database: Package 'pvt.cppan.demo.leptonica' not found.
Trying origin remote
Requesting dependency list...
Some packages (1) are unresolved
```

**Comment by egorpugin** [comment]
It's true. What file are you processing?
https://cppan.org/pvt.cppan.demo.danbloomberg.leptonica

**Comment by zdenop** [comment]
I just try to build tesseract 3.05 on windows with fresh VS2015 installation ;-)...

**Comment by egorpugin** [comment]
I did not fix cppan.yml in old version branches.

**Comment by egorpugin** [comment]
See https://github.com/tesseract-ocr/tesseract/commit/73890c38bb522b0b3312c070a29c8db8ea25efab

**Comment by zdenop** [comment]
Thanks.
