### ISSUE TITLE
When I run cppan under windows 10 it can't find the git.exe path

### ISSUE THREAD

**Issue by gjmjack** [cppan/cppan#12]
when I'm trying to run cppan under directory "tesseract-master", I got the following error:

_Downloading database
Command failed: C:\Program Files (x86)\git.exe
Cannot get dependencies from local database: boost::process::detail::win32_start: CreateProcess failed: System can't find the file specified.
Requesting dependency list...
Reading package specs..._

but my git.exe is installed under C:\Program Files (x86)\git\bin, how can it find that under the C:\Program Files (x86)\ path.

Is there anyway to configure this? Or how can make this success?

**Comment by egorpugin** [comment]
Hi,

I'm not sure, but it's somehow related to your environment (PATH) variable.
Cppan resolves git to C:\Program Files (x86)\git.exe in your system.

Anyway, does cppan work regardless of this error?
Because as a fallback, cppan will download the database manually.

**Comment by gjmjack** [comment]
Hi egorpugin,

Thanks for your quick response.
If as you said it will fallback to download manually, I did see it was downloading some packages.
And now if I re-run this command it just show the above information.

By the way how to setup the PATH environment variable to let it working perfectly? I check that setting, currently I got "C:\Program Files (x86)\Git\cmd" configured.

**Comment by egorpugin** [comment]
> And now if I re-run this command it just show the above information.

In general that's ok. Probably, I could hide it.

> By the way how to setup the PATH environment variable to let it working perfectly?

I'm not the best person to answer this. :) Try to google it.
Try to run `where git` from windows command line. It will show you where windows resolve git.exe on your system.

**Comment by gjmjack** [comment]
> Try to run where git from windows command line. It will show you where windows resolve git.exe on your system.
I run this command and it got: 
C:\Program Files (x86)\Git\cmd\git.exe
If so, I believe my PATH setting is correct.

Anyway, thanks. this command **where git** is useful I didn't use that before. :)

**Comment by egorpugin** [comment]
I'll update the client in a few minutes, so you could try and see if your issue is fixed. I'll ping here.

**Comment by egorpugin** [comment]
Ok, I've updated the client.
Please, run `cppan --self-upgrade`. And then your usual cppan command to see if any error exists.

**Comment by gjmjack** [comment]
the error has gone! Cheers @egorpugin
