### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by varun1994varun** [cppan/cppan#17]
Hi,I am trying to build with the steps as  you mentioned.
git clone https://github.com/cppan/cppan cppan_client
cd cppan_client
cppan

But when I enter cppan in cmd it gives following message.
Cannot get dependencies from local database: Package 'pvt.cppan.demo.boost.program
_options' not found.
Requesting dependency list...
Retrying...
Retrying...
Could not connect to server
curl error: Timeout was reached.

Please help me on this.
Thank you.

**Comment by egorpugin** [comment]
Do you have a proxy? Maybe the issue with network?
