### ISSUE TITLE
Linking problem on Macos

### ISSUE THREAD

**Issue by coding3d** [cppan/cppan#2]
Hi Egor,

I have added small3d on cppan under my account:

https://cppan.org/pvt.coding3d.small3d/version/1.0.4

One little issue is that I uploaded a tgz archive to begin with, then deleted the version and re-created it, linking to the github repository, but unfortunately I still see the uploaded archive. Perhaps it did not get deleted when I deleted the version?

The main thing though is that, on Macos, when I compile the small3d_example project, either referencing my own package or the small3d package you had created, I get some linking errors:

```
Undefined symbols for architecture x86_64:
  "_COCOA_bootstrap", referenced from:
      _SDL_VideoInit_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
      _bootstrap in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_IsWindowInFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
      _SDL_OnWindowFocusLost in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_SetWindowFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_ShowMessageBox", referenced from:
      _SDL_ShowMessageBox_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_SDL_GetBasePath_REAL", referenced from:
      _SDL_DYNAPI_entry in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_dynapi.c.o)
  "_SDL_GetPrefPath_REAL", referenced from:
      _SDL_DYNAPI_entry in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_dynapi.c.o)
  "_SDL_NSLog", referenced from:
      _SDL_LogOutput in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_log.c.o)
  "_SDL_OpenFPFromBundleOrFallback", referenced from:
      _SDL_RWFromFile_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_rwops.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/main] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2
```
I think that this can be resolved by linking to these libraries from a local CMakeLists file, but is there a way to configure a cppan package to link to some standard libraries when compiling on certain operating systems? This might be useful in the long run.

**Comment by egorpugin** [comment]
Yes, I saw this issue yesterday too.
We've already have automatic linking of Ws2_32.lib on win32, pthread on linux.
I just did not test macOS much.
Will try to fix it today.

> but unfortunately I still see the uploaded archive

cppan extracts you source codefiles and stores them in an archive.
Only owner can see that link. Look at demo https://cppan.org/pvt.cppan.demo.coding3d.small3d/version/1.0.4
You do not see this link.

**Comment by coding3d** [comment]
Alright, good then! I thought that the archive was a leftover from the version I had created earlier. I have to say, it's quite impressive how easily projects get set up on cppan, disregarding the aforementioned linking issue.

**Comment by egorpugin** [comment]
> how easily projects get set up on cppan

That's the goal :)

---
I see you removed cppan.yml from your develop branch. And seems you've chosen the way with manual cppan.yml upload. This is possible and you can do this without exceptions and limitations, but the original intent was to keep cppan.yml in the repo, so server will read it after repo checkout.

For example, you've changed something in the repo, added a new dependency or whatever and right after that you've fixed `cppan.yml`, made a release and upload it to cppan server.
If you don't have `cppan.yml` you need to go to cppan.org, take old cppan.yml, make a change, upload it there again.
Not so great workflow.
---
And one more thing.
After release or in late beta, cppan server will deny versions removal because of security considerations.
You'll have about a week to test your submission, verify that it works and do a commit (or server will commit version for you).
During that test week, cppan server won't show this version to users, you will be able to do a "force" download of it for testing purposes.
After version is fixed, it will appear for everyone.

This affects only versions.
Branches are always considered as unstable, feel free to remove them, add again, update etc.

**Comment by coding3d** [comment]
Hehe! First tries, so I'm not 100% sure what I'm doing. :bowtie: I will re-introduce the cppan.yml file, like you suggest. Thanks for the rest of the info. I'll keep it in mind.

**Comment by coding3d** [comment]
Ok, I've re-added cppan.yml to the develop branch. Of course, since version 1.0.4 was already tagged, it will in effect be used for version 1.0.5. I am also mentioning your example in the new [README](https://github.com/coding3d/small3d/blob/develop/README.md)

**Comment by egorpugin** [comment]
Nice, thanks!
I tried to fix SDL issue today, but did not succeed.
Cocoa framework is linked to SDL, but for some reason it still does not see those symbols.
Need more investigations.
In other words, the issue is not in cppan itself but in SDL package that I added.

**Comment by egorpugin** [comment]
And here is an example of branch versions on cppan.
https://cppan.org/pvt.cppan.demo.coding3d.small3d/version/develop
But at the moment I used custom `cppan.yml` instead of using your version from git.
Because you have incorrect field there: `version` and `source`. They are filled on website.

**Comment by coding3d** [comment]
As far as I know, SDL is quite a tough cookie to compile in general. I'll let you know if I come accross any useful info...

**Comment by egorpugin** [comment]
Also you can copy-paste `cppan.yml` contents to http://www.yamllint.com/ to get it to readable view.
At the moment cppan uses `yaml-cpp` library which has bug when saving multiline string.

**Comment by coding3d** [comment]
Ah, yes, I just copy pasted it from cppan.org. How is it looking now?

https://github.com/coding3d/small3d/blob/develop/cppan.yml

Of course, the tag that is listed in it does not exist yet...

**Comment by coding3d** [comment]
Difficult to educate, aren't I? :) How about now?

https://github.com/coding3d/small3d/blob/develop/cppan.yml

**Comment by egorpugin** [comment]
Looks good now.
With it you can try to add your branch choosing `From git repository` item.
Put a link to your github repo there and write `develop` to `version` and `branch` fields.

**Comment by coding3d** [comment]
Like this?

https://cppan.org/pvt.coding3d.small3d/version/develop

:)

I did get the following little problem trying to compile the demo with this one though:

The following imported targets are referenced, but are missing:
  pvt.cppan.demo.glm-0.9.8

It's funny because glm seems to be on the site... (using Macos now)

**Comment by egorpugin** [comment]
Try to run
```
cppan --clean-projects pvt.cppan.demo.glm.*
```
And the run build again.

**Comment by coding3d** [comment]
After this command, when I build, I see indeed that glm is re-downloaded:

Downloading: pvt.cppan.demo.glm-0.9.8... Ok
Unpacking  : pvt.cppan.demo.glm-0.9.8... Ok

However, then I still get the same error. The interesting detail is that, if I switch to using my 1.0.4 version of small3d (so, not the develop branch), this doesn't happen...

**Comment by coding3d** [comment]
Are we sure my develop version looks ok?

**Comment by egorpugin** [comment]
Ah, develop version is the issue. Let me try...

**Comment by egorpugin** [comment]
Ok, same for me.
Diving into debug :)

**Comment by coding3d** [comment]
:D Remember, I am doing all of this on Macos right now.

**Comment by egorpugin** [comment]
Should not matter actually.
The design is very crossplatform. (Atleast I hope so :) )

**Comment by coding3d** [comment]
Nonetheless, I try to report in detail :)

**Comment by egorpugin** [comment]
Seems I've fixed it locally.

**Comment by egorpugin** [comment]
The not so good news is that I haven't good testing tools now.
I can upload it on our risk :)

**Comment by egorpugin** [comment]
The change does not look very dangerous though.

**Comment by coding3d** [comment]
For me it's not urgent but I'll test if you post a new version. I enjoy a bit of danger 😜

**Comment by egorpugin** [comment]
Ok, try to
```
cppan --version
sudo cppan --self-upgrade
cppan --version
```

**Comment by egorpugin** [comment]
And try to build with develop version of small3d.

**Comment by coding3d** [comment]
The way you're making everything so easy (even the upgrade) is going to give you a lot of feedback from users I think. Even when looking into glitches cppan is not tiring at all. 👍 
Anyway, that worked. Still, the same version is reported (0.1.8) but now it compiles up to the point where the SDL linking problem occurs. By the way, I did not sudo because the executable is located in a directory under my home folder. I suppose that's ok?

**Comment by egorpugin** [comment]
Yes, just make sure it's in PATH.

**Comment by coding3d** [comment]
That it is :)

**Comment by egorpugin** [comment]
Should be fixed now. Works for me on macos.
The issue is that I did not declare *.m files to be taken intothe sdl archive.

**Comment by egorpugin** [comment]
If you see any issues try to run `cppan --clean-projects pvt.cppan.demo.valve.*`.

**Comment by coding3d** [comment]
Hi Egor,

I have performed the upgrade procedure. If I execute cppan --version, I get:

```
cppan version 0.1.8
assembled 2016-Sep-15 21:20:40
```

The first time I executed cppan --build main.cpp (after cleaning valve.* with the command you mentioned above), I got the following result:

```
-- Configuring done
CMake Error at cppan/helpers.cmake:278 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:pvt.coding3d.small3d-develop>

  No target "pvt.coding3d.small3d-develop"
Call Stack (most recent call first):
  cppan/CMakeLists.txt:30 (include)


-- Generating done
-- Build files have been written to: /var/folders/xq/c0cmdw9n0n3fcd58_l_wwh7c0000gn/T/cppan/build/8ac145/x86_64-appleclang-7.0-64/build
```

Then, I re-executed it, and got the usual linker errors:

```
Undefined symbols for architecture x86_64:
  "_COCOA_bootstrap", referenced from:
      _SDL_VideoInit_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
      _bootstrap in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_IsWindowInFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
      _SDL_OnWindowFocusLost in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_SetWindowFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_Cocoa_ShowMessageBox", referenced from:
      _SDL_ShowMessageBox_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_video.c.o)
  "_SDL_GetBasePath_REAL", referenced from:
      _SDL_DYNAPI_entry in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_dynapi.c.o)
  "_SDL_GetPrefPath_REAL", referenced from:
      _SDL_DYNAPI_entry in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_dynapi.c.o)
  "_SDL_NSLog", referenced from:
      _SDL_LogOutput in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_log.c.o)
  "_SDL_OpenFPFromBundleOrFallback", referenced from:
      _SDL_RWFromFile_REAL in libpvt.cppan.demo.valve.sdl.sdl-2.0.4.a(SDL_rwops.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/main] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2
```

Let me know if there is anything else I can try. Sorry to be the bearer of bad news :(

**Comment by egorpugin** [comment]
Try more and more :)
It works for me in 3-5 attempts.
Or you could try to remove `~/.cppan/storage` and re-try again. (In this way it probably will work near 100% prob.)

**Comment by egorpugin** [comment]
Also you could try to `cd $TMPDIR` and remove from it `cppan` folder.

**Comment by coding3d** [comment]
Why didn't you say so? :) Ok, I've made a full cleanup, including the cppan folder from $TMPDIR and now the game compiled. However, when the bug touches the goat, it is supposed to make a bah sound. Instead, the game exits (meaning there is an exception) and there is the following error:

`2016-09-16 19:42:09 - ERROR: No default sound output device.`

This could be a linking error that has to do with portaudio, but I am not sure. Specifically on Macos, the following is needed in the CMakeLists.txt file when linking with cmake for example:

```
IF(APPLE)
  FIND_LIBRARY(AUDIOUNIT_LIBRARY AudioUnit)
  FIND_LIBRARY(AUDIOTOOLBOX_LIBRARY AudioToolbox)
  FIND_LIBRARY(COREAUDIO_LIBRARY CoreAudio)
  TARGET_LINK_LIBRARIES(small3d PUBLIC ${COREAUDIO_LIBRARY} ${AUDIOUNIT_LIBRARY} ${AUDIOTOOLBOX_LIBRARY})
ENDIF(APPLE)
```
And I think there are more, but they are already added by SDL or something, so I am not adding them myself. It is some system libraries, not directly related to sound.

On the other hand, this could be a more generic portaudio configuration error because it's true that there was no linking problem... It looks to me a lot like a problem that I had on Ubuntu, which I never got to investigate too deeply...

**Comment by egorpugin** [comment]
Yeah, I see no sound too and that error. Error is somewhere inside sdl?/portaudio/small3d

**Comment by coding3d** [comment]
SDL has sound capabilities, but I am not using them at all. It is a separate library called sdl_sound or something like that. Portaudio can be tough to build correctly sometimes. On every system, it can link to more than one sound libraries... In general, I don't know if this default device can be selected more actively through code, or if the reported problem is not what it says at all (maybe no default device means that there is no available device, according to portaudio's "understanding" of the situation. I am not sure...)

**Comment by coding3d** [comment]
The small3d codebase could handle the sound situation much better. Before I try to play the sound, I could try to scan the device status and handle any potential problems, even turning off the sound if it is not available before the game crashes. I am working on my rotations now and then I have to look into the parsing of some file formats but, at some point, I will review the sound system. Appart from this problem, a similar one to which I have on Ubuntu, there is a noise problem on Debian (resolved for now by bypassing Pulse Audio) and there is also the fact that, on Macos, even the independent build and the conan.io build are linking to a deprecated sound API. In conclusion, I think that cppan is working quite well already and I am not sure if trying to resolve this particular issue, from your side, is very important at this point. Better focus on other priorities. Either way, the linking problem I initilally reported here has now gone away, so I am closing this issue 👍

**Comment by egorpugin** [comment]
To debug this issue in Xcode you could try to replace cppan settings in `main.cpp` with next code:
```
/*
local_settings:
    build_dir_type: local
    use_cache: false
    build:
        cxx_flags: -std=c++11
        use_shared_libs: false
        generator: Xcode
files:
    - GameLogic.cpp
    - main.cpp
dependencies:
    pvt.cppan.demo.coding3d.small3d: 1
    pvt.cppan.demo.valve.sdl.sdlmain: 2
*/
```

The directory `cppan-build-main.cpp/{config}/build` will be created with xcode project inside.
If the issue is not in your code, it's somewhere in configuration of one of these packages used by small3d.

**Comment by egorpugin** [comment]
And they are only demo versions :) (remember `pvt.cppan.demo` namespace?)

**Comment by coding3d** [comment]
I'll try that. It may take a few days but I'll report back :)
I know they're demo versions but they're working quite well so I might as well try and get small3d running 100% well :D

**Comment by dimi309** [comment]
Hi Egor. Could you delete my coding3d account? I would like to recreate it with a different e-mail address. To cut a long story short, I was cleaning up my accounts and I thought to get rid of the address I used, but I forgot that it was associated with my cppan account. There's no way to get it back now.

**Comment by egorpugin** [comment]
Actually not a problem. I have "remove account" feature on my todo list. But for now I can do it manually. 
And a small issue here :) I'm not at home till the end of the weekend, so I dont have an access to server. I'll do this when Im back.

By the way I can just change an email for you if you're ok with your account name.

Or you can create a new account right now, upload your project and I'll delete your account later.

**Comment by dimi309** [comment]
Changing the address will be just fine. Could you put d i m k o u r (w/o spaces) at the same domain as the old one? It's not urgent. I've still got a bit of work to do before looking into the sound system and updating the cppan version of my little project. I do remember my password so, no problem there.

**Comment by egorpugin** [comment]
Ok, will do that.

**Comment by egorpugin** [comment]
Hi @dimi309,

Instead of changing your email I've added such function to CPPAN website.
Check out your user account page -> settings and try to change email there.

**Comment by dimi309** [comment]
Hi Egor,

I'm getting this message:

```
We have improved our security, so please reset your password via "Forgot password?" function.
Feel free to keep your password the same, it is safe.
```

I guess I've forgotten my password... Could you trigger a reset somehow, but not using my former e-mail? sorry... :(

**Comment by egorpugin** [comment]
Ok, I've updated your email, try to login into your account (after pw reset).

**Comment by dimi309** [comment]
Alright! We're back in business!! Thanks a lot! I've made many changes and I'm about to review the sound handling issue with PortAudio. If it can't find a device, I'll make it not crash at least.
