### ISSUE TITLE
is it possible to set multi processor build for Visual Studio?

### ISSUE THREAD

**Issue by estekitaly** [cppan/cppan#28]
I'm trying to build tesseract OCR https://github.com/tesseract-ocr/tesseract/tree/3.05 for Visual Studio (2015 or 2017)

in the .yml inside the repository I see "#generator: Visual Studio 14 2015 Win64" but not other reference to visual studio, or visual studio specific settings.

is it possible to somehow set the "/m" flag, that enables multi processor build, for MSBUILD in CPPAN or is there any other way to tell Visual Studio to use multi processor build from CPPAN?

I know that Inside visual studio you can change the multi processor setting under "Tools>options>Projects and Solutions>Build and Run" and I have already set it.

**Comment by egorpugin** [comment]
What is multiprocessor build?

**Comment by estekitaly** [comment]
multiprocessor build in visual studio is an option to allow the compiler to spawn multiple compiling threads, so the code can compile faster

**Comment by egorpugin** [comment]
It should be enabled by default.

**Comment by estekitaly** [comment]
ok, thank you!
