### ISSUE TITLE
[Website] FAQ link leading to github main page

### ISSUE THREAD

**Issue by Ninetainedo** [cppan/cppan#3]
Hello,

I wanted to see the FAQs and noticed that the link on the frontpage of the website (Supposed to point to https://github.com/cppan/cppan/wiki/F.A.Q.) brings me back to the homepage of the Github project (https://github.com/cppan/cppan)

**Comment by egorpugin** [comment]
Thanks! Fixed.
Faq is very poor now, sorry. I'll be filling  it continuously. Feel free to ask any interested questions.
If you need more info:
Check other files in `doc` dir of a client.
Please, check demo example, some other examples in https://github.com/cppan
Maybe check this video https://www.youtube.com/watch?v=VE9TJJfwDEY and that channel.

**Comment by Ninetainedo** [comment]
I just wanted to know where does cppan download/generate stuff ?

**Comment by egorpugin** [comment]
$HOME/.cppan/storage
or for windows in %USER% or whatever is user home folder.

**Comment by egorpugin** [comment]
Added this info to faq, also the way how to change it.
https://github.com/cppan/cppan/blob/master/doc/faq.md

**Comment by Ninetainedo** [comment]
Exactly what I needed, thanks !
