### ISSUE TITLE
Link errors in pvt.cppan.demo.boost.test-1.65.0 witn Visual Studio 15 (Win64 or x86)

### ISSUE THREAD

**Issue by biocomp** [cppan/cppan#32]
Getting link error while cmake tries to build boost test for me.

So a couple of questions:

    1. What am I doing wrong? What info do you need from me to figure out the issue? 
    2. Is there a way to build static version of boost.test? I was not able find examples of it, and looks like E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\ce7769c8\cppan\439c6283\439c6283.vcxproj project mentioned below only builds DynamicLibrary.

Some context:
**Error:**
```
       Creating library E:/Win81Users/artyomt/.cppan/storage/lib/eb6c0f72/Debug/pvt.cppan.demo.boost.test-1.65.0.lib and object E:/Win81Users/artyomt/.cppan/storage/lib/eb6c0f72/Debug/pvt.cppan.demo.boost.test-1.65.0.exp
test_main.obj : error LNK2019: unresolved external symbol "int __cdecl test_main(int,char * * const)" (?test_main@@YAHHQEAPEAD@Z) referenced in function "public: void __cdecl test_main_caller::operator()(void)" (??Rtest_main_caller@@QEAAXXZ) [E:\Win81Users\art yomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.vcxproj] [E:\Win81Users\artyomt\Source\Repos\CloudBuildAnalyzer\debug_build\.cppan\cppan-d-b-d.vcxproj]
E:\Win81Users\artyomt\.cppan\storage\bin\eb6c0f72\Debug\pvt.cppan.demo.boost.test-1.65.0.dll : fatal error LNK1120: 1 unresolved externals [E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.vcxproj] [E:\Win81Users\artyo mt\Source\Repos\CloudBuildAnalyzer\debug_build\.cppan\cppan-d-b-d.vcxproj]
```

**Full link command** 
(and I checked - test_main.obj does contain int __cdecl test_main(int,char * * const) (?test_main@@YAHHQEAPEAD@Z) with matching signature to the error above:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\Win81Users\artyomt\.cppan\storage\bin\eb6c0f72\Debug\pvt.cppan.demo.boost.test-1.65.0.dll" /INCREMENTAL /NOLOGO "E:\Win81Users\artyomt\.cppan\storage\lib\eb6c0f72\Debug\pvt.cppan.demo.boost.timer-1.65.0.lib" Ws2_32.lib "E:\Win81Users\artyomt\.cppan\storage\lib\eb6c0f72\Debug\pvt.cppan.demo.boost.chrono-1.65.0.lib" "E:\Win81Users\artyomt\.cppan\storage\lib\eb6c0f72\Debug\pvt.cppan.demo.boost.system-1.65.0.lib" Ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/Win81Users/artyomt/.cppan/storage/bin/eb6c0f72/Debug/pvt.cppan.demo.boost.test-1.65.0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/Win81Users/artyomt/.cppan/storage/lib/eb6c0f72/Debug/pvt.cppan.demo.boost.test-1.65.0.lib" /MACHINE:X64  /machine:x64 /DLL E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\version.res E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\compiler_log_formatter.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\cpp_main.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\debug.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\decorator.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\execution_monitor.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\framework.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\junit_log_formatter.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\plain_report_formatter.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\progress_monitor.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\results_collector.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\results_reporter.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\test_framework_init_observer.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\test_main.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\test_tools.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\test_tree.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\unit_test_log.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\unit_test_main.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\unit_test_monitor.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\unit_test_parameters.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\xml_log_formatter.obj E:\Win81Users\artyomt\.cppan\storage\obj\43\9c\6283\build\9f97051f\cppan\439c6283\439c6283.dir\Debug\xml_report_formatter.obj`

**cppan.yaml**
```
dependencies:
    pvt.cppan.demo.boost.filesystem: 1.65
    pvt.cppan.demo.boost.test: 1.65
```

**Cmake command (run from project root, after cppan was executed there):**
```
"c:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 Win64" -Bdebug_build -H.
"c:\Program Files\CMake\bin\cmake.exe" --build debug_build
```

**Comment by biocomp** [comment]
Looks like the answer to my question #2 is here: https://github.com/cppan/cppan/issues/13, will try.

**Comment by biocomp** [comment]
Ok, when I changed cppan.yaml to:
```
local_settings:
    use_shared_libs: false

    dependencies:
        pvt.cppan.demo.boost.filesystem: 1.65
        pvt.cppan.demo.boost.test: 1.65

# your project settings
shared_only: true
```

boost.test was built successfully into .lib. But I had to clear cppan cache manually.
However, now my UT project fails to link with the same problem:
`Error	LNK2019	unresolved external symbol "int __cdecl test_main(int,char * * const)" (?test_main@@YAHHQEAPEAD@Z) referenced in function "public: void __cdecl test_main_caller::operator()(void)" (??Rtest_main_caller@@QEAAXXZ)	parser_test	E:\Win81Users\artyomt\Source\Repos\CloudBuildAnalyzer\debug_build\test\pvt.cppan.demo.boost.test-1.65.0.lib(test_main.obj)	1	`

**Comment by biocomp** [comment]
Ok, my bad. Looks like both of the times I forgot to setup my own test module, so it was legitimate link failure in boost.test. All my fault. 

Sorry for the noise!

**Comment by egorpugin** [comment]
Hi,

Yes, boost.test requires something (your main() or whatever) from user IIRC.
And still note that I uploaded a lot of packages as experimental and did not test them all.
Some basic boost packages may works, some others may not.
