### ISSUE TITLE
[Questtion] how to build 64 bit

### ISSUE THREAD

**Issue by hoangtocdo90** [cppan/cppan#35]
Hello guys!
Thanks for make a great software.
I'm not know c++ but i usually using cppan for build some c++ open source binary.
It's help me so much time
I'm install cppan + visual studio + cppan and simply using this command like
cppan --build pvt.cppan.demo.google.tesseract.tesseract-master . 
 but how to build 64 bit by this command and can i remove pvt.cppan.demo for every dll?
Thanks for reading

**Comment by egorpugin** [comment]
Hi,

1. To build 64 binaries create a file `cppan.yml` in your current directory and put there:
```
local_settings:
    generator: Visual Studio 15 2017 Win64
```
Replace `15 2017` with your Visual Studio version according to cmake generators list https://cmake.org/cmake/help/v3.10/manual/cmake-generators.7.html#visual-studio-generators
Then run you commands in this dir.

2. It's not currently possible to remove that prefix from filenames.

**Comment by hoangtocdo90** [comment]
@egorpugin thanks for reply
it't so great if  you add some thing like this parameter cppan --generator "Visual Studio 15 2017 Win64" direct in command line .
Thanks so much !

**Comment by egorpugin** [comment]
This will be in the next major release (cppan2).

**Comment by BudiKusasi** [comment]
Must God blesses you
in a webpage of Compiling Tesseract
...
To do this:

   1. Download <https://cppan.org/client/cppan-master-Windows-client.zip> the
   latest CPPAN (C++ Archive Network https://cppan.org/) client from
   https://cppan.org/client/.
   2. Run cppan --build pvt.cppan.demo.google.tesseract-master


I did till point 2. but then it gave:

No such file or directory, trying to build as package
Reading package specs...
--
-- Performing test run
--
Generating build files...
Run command '"cmake" "-HD:/MSYS/tmp/cppan/temp/ef97-4234-b1bb-456d"
"-BD:/MSYS/tmp/cppan/temp/ef97-4234-b1bb-456d/build"
"-DCMAKE_BUILD_TYPE=Release"
"-DCPPAN_COMMAND=D:/app/Git/cmd/cppan.exe" "-DCPPAN_CMAKE_VERBOSE=0"
"-DCPPAN_BUILD_VERBOSE=1" "-DCPPAN_BUILD_WARNING_LEVEL=0"', error: no
such file or directory


How to solve this ? and let me yo know that I haven't installed Cmake and not known how to do it.. 
Many thanks in advance !

**Comment by egorpugin** [comment]
Download & install cmake from cmake.org.

**Comment by BudiKusasi** [comment]
Where'd I put all cmake executables among directories
