### ISSUE TITLE
cppan on centos

### ISSUE THREAD

**Issue by avestnik** [cppan/cppan#37]
please advise if cppan supports centos. I get the following error trying to install it:

[~]# yum install cppan-master-Linux-client.rpm
Loaded plugins: fastestmirror
Examining cppan-master-Linux-client.rpm: cppan-client-0.2.3-1.amd64
Cannot add package cppan-master-Linux-client.rpm to transaction. Not a compatible architecture: amd64
Error: Nothing to do

or 

[~]# rpm -i cppan-master-Linux-client.rpm
error: Failed dependencies:
        libc.so.6(GLIBC_2.18)(64bit) is needed by cppan-client-0.2.3-1.amd64
        liblber-2.4.so.2(OPENLDAP_2.4_2)(64bit) is needed by cppan-client-0.2.3-1.amd64
        libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit) is needed by cppan-client-0.2.3-1.amd64

**Comment by egorpugin** [comment]
Hi,

I had centos rpms somewhere.
Currently linux versions can be bugged because of lack of proper testing.

I'll try to create a new rpm for you.

> libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit) is needed by cppan-client-0.2.3-1.amd64

It seems you should install libldap first to fix this issue.

> libc.so.6(GLIBC_2.18)(64bit) is needed by cppan-client-0.2.3-1.amd64

I'll check about static linking of libc.

**Comment by avestnik** [comment]
thanks for prompt reply. actually, I tried centos after not being able to run cppan on win10 x64. it just crashes with segfault during tesseract build. I narrowed it down to empty c++ project with a single dependency on leptonica. if I run cppan again after crash it complains about missing leptonica in local database

**Comment by avestnik** [comment]
and yes, ldap is there, but in /usr/lib64. I guess cppan expects them to be in /lib64

[~]# find / -name libldap\*
/usr/lib64/libldap-2.4.so.2
/usr/lib64/libldap-2.4.so.2.10.7
/usr/lib64/libldap_r-2.4.so.2
/usr/lib64/libldap_r-2.4.so.2.10.7

**Comment by egorpugin** [comment]
I see. Looks like bad binary.
Are you using centos 7? 7.4?

**Comment by avestnik** [comment]
latest one centos-release-7-4.1708.el7.centos.x86_64

**Comment by egorpugin** [comment]
Unfortunately I can't help you fast enough, sorry.

You could try this debug binary I've just built to check your lib issues.
https://www.dropbox.com/s/cms29m1ky7cbj2e/cppan?dl=1

You'll see many crashes, ignore and retry, it may process slowly.

**Comment by avestnik** [comment]
it successfully started but doesn't work. it hung processing tesseract somewhere around pango
Cleaning   : pvt.cppan.demo.gnome.pango.pangocairo-1.40.9... (lib, bin)
Cleaning   : pvt.cppan.demo.gnome.pango.pangoft2-1.40.9... (lib, bin)
Cleaning   : pvt.cppan.demo.gnome.pango.pango-1.40.9... (lib, bin)

and after several restarts it hung completely

**Comment by egorpugin** [comment]
Cannot afree here. Cleaning is a very long step. It's true even on release version, so you might need wait for a very long time.
I think I found workaround about crashes, so I'll try to prepare a release build for you.

**Comment by egorpugin** [comment]
Please, check this one. It's a release buid, the latest master.
https://www.dropbox.com/s/l7e7fxziyuwfnks/cppan-master-Linux-client.rpm?dl=1

**Comment by egorpugin** [comment]
FYI: personally I still experience one issue on centos. I'll check later.
You may see something like this:
```
Make Error at /home/egor/.cppan/storage/etc/static/functions.cmake:676 (message):
  Last execute_process() with message '' failed with error: No such file or
  directory
Call Stack (most recent call first):
  /home/egor/.cppan/storage/etc/static/build.cmake:178 (check_result_variable)
  /home/egor/.cppan/storage/obj/e5/e6/4d86/build.cmake:43 (include)
```

**Comment by egorpugin** [comment]
Can you simply extract binary?

**Comment by avestnik** [comment]
I did and it worked. I was able to run it for cppan_client itself. but cmake && make failed with the message you posted 2 days ago

**Comment by egorpugin** [comment]
Yes, strange issue. Cppan works on ubuntu but not on centos.

**Comment by avestnik** [comment]
well, I came back to win10. can you please build win client from most recent source? client available on web site for some reason can not find leptonica. if you need I can post error log

**Comment by egorpugin** [comment]
RelWithDebInfo [cppan.zip](https://github.com/cppan/cppan/files/1578611/cppan.zip)

**Comment by avestnik** [comment]
it fails under mingw64
$ cppan ../tesseract/
Segmentation fault

but works well from command promt and I managed to build tesseract on vs2017

**Comment by egorpugin** [comment]
I did not do any tests w/ mingw64.
How do you invoke it? I've tried mingw64 from git, works fine.

**Comment by avestnik** [comment]
I use mingw64 that goes with msys2 and just run windows executable from mingw64 prompt

**Comment by arcral** [comment]
I also met this question: Not a compatible architecture: amd64. 
It seems not been solved

**Comment by egorpugin** [comment]
@arcral Sorry, the development focus is on sw (cppan v2) right now.
Support for wide range of distros will be performed more carefully there.
