### ISSUE TITLE
openjp2 is buggy on Little Endian machines

### ISSUE THREAD

**Issue by linquize** [cppan/cppan#38]
package: `pvt.cppan.demo.openjpeg.openjp2`

Because opnejp2 internally checks whether `OPJ_BIG_ENDIAN` is defined `#if defined(OPJ_BIG_ENDIAN)` in `cio.h`,
it generates `opj_config_private.h` having `# define OPJ_BIG_ENDIAN 0`.
But this still enables the option, which is wrong on Little Endian (x86, x64, ARM) machines.

In `cppan.yml`,
```
# define OPJ_BIG_ENDIAN @WORDS_BIGENDIAN@
```

Should change to 
```
#if @WORDS_BIGENDIAN@
#define OPJ_BIG_ENDIAN @WORDS_BIGENDIAN@
#endif
```

**Comment by egorpugin** [comment]
Fixed, thanks.
