### ISSUE TITLE
Cppan does not work with spaces in user name

### ISSUE THREAD

**Issue by egorpugin** [cppan/cppan#39]
cc: @QuantumLiu

**Comment by QuantumLiu** [comment]
@egorpugin Thank you very much！

**Comment by AiQLee** [comment]
The cppan will automatically generate a .cppan folder in C:\Users\#YourName#\.cppan    
Then you can find a file called cppan.yml and a folder called storage inside it. Open it and edit the line
"storage_dir: C:\Users\#YouName#\.cppan\storage"
to 
"storage_dir: C:\.cppan\storage"

Next, copy the .cppan folder to your root, which is C:\
Maybe it will work.

**Comment by oulrich1** [comment]
This still seems to be an issue, Compiling locally to see if i can resolve it. Unless someone else already has a solution?

**Comment by egorpugin** [comment]
CMake side is the issue. There are so many unquoted paths there.
You could start it from there.

**Comment by egorpugin** [comment]
Please, proceed to sw https://github.com/SoftwareNetwork/sw
