### ISSUE TITLE
Adding appveyor CI support

### ISSUE THREAD

**Issue by Telokis** [cppan/cppan#4]
What about adding a [Appveyor](https://www.appveyor.com/) CI as well ?
It will make cppan run inside Windows instead of Linux.
It's possible to use `bash -c` commands to minimize the amount of things to change from travis.

**Comment by egorpugin** [comment]
What do you mean here? :)
Testing is not working at all atm.
I'm investigating the best ways of handling it.

**Comment by Ninetainedo** [comment]
Well. I saw the `.travis.yml` file. Since Travis is linux/osx based, I thought it would be nice to use something able to test the project against Windows as well.
That's what Appveyor is meant to do ! It's basically Travis for Windows.

**Comment by egorpugin** [comment]
yes, i know. 
testing is on my roadmap.
i'll return to it a bit later.
currently im trying to add more well known packages to see what needs and what challenges are there.
projects like opencv or qt.
header only and simple projects are handled well enough already.

**Comment by egorpugin** [comment]
as for testing
i need a  tool that will be iterating over different configuration and building them

**Comment by Ninetainedo** [comment]
Alright, I didn't understand it that way.
The Travis file misled me I guess.

**Comment by egorpugin** [comment]
Appveyor seems to be working now.
https://ci.appveyor.com/project/egorpugin/cppan/history
