### ISSUE TITLE
How create tesseract executable ?

### ISSUE THREAD

**Issue by BudiKusasi** [cppan/cppan#40]
I tried to build tesseract and followed the instructed steps in a Wiki page:

Build the latest library :

- Download the latest CPPAN (C++ Archive Network https://cppan.org/) client from https://cppan.org/client/.
- Run cppan --build pvt.cppan.demo.google.tesseract.tesseract-master

so I typed
$ cppan --build pvt.cppan.demo.google.tesseract.tesseract-master

but returned:

-- Building for: NMake Makefiles
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
No such file or directory, trying to build as package
Reading package specs...
--
-- Performing test run
--
Generating build files...
CMake Error at CMakeLists.txt:39 (project):
CMake Error at CMakeLists.txt:39 (project):
CMake Error at CMakeLists.txt:39 (project):
CMake Error at CMakeLists.txt:39 (project):
CMake Error at CMakeLists.txt:39 (project):
CMake Error at CMakeLists.txt:39 (project):
-- Configuring incomplete, errors occurred!
See also "D:/MSYS/tmp/cppan/temp/1e2a-8152-9e5c-7649/build/CMakeFiles/CMakeOutput.log".
See also "D:/MSYS/tmp/cppan/temp/1e2a-8152-9e5c-7649/build/CMakeFiles/CMakeError.log".
Run command '"D:\APP\cmake3.10\bin\cmake.exe" "-HD:/MSYS/tmp/cppan/temp/1e2a-8152-9e5c-7649" "-BD:/MSYS/tmp/cppan/temp/1e2a-8152-9e5c-7649/build" "-DCMAKE_BUILD_TYPE=Release" "-DCPPAN_COMMAND=D:/APP/cmake3.10/bin/cppan.exe" "-DCPPAN_CMAKE_VERBOSE=0" "-DCPPAN_BUILD_VERBOSE=1" "-DCPPAN_BUILD_WARNING_LEVEL=0"', error: operation not permitted

even if cmake and CPPAN were ready put in the Path env. var
How to solve my problem... Many thankfulness in advance..

**Comment by egorpugin** [comment]
MSYS is not tested at all.
Try to build with Visual studio.
