### ISSUE TITLE
Local db data caused issues, trying remote one

### ISSUE THREAD

**Issue by hoangtocdo90** [cppan/cppan#41]
Some things was wrong
 cppan --build pvt.cppan.demo.danbloomberg.leptonica .
No such file or directory, trying to build as package
Downloading: pvt.cppan.demo.xz_utils.lzma-5.2.3...
Downloading: pvt.cppan.demo.danbloomberg.leptonica-1.75.1...
Downloading: pvt.cppan.demo.jpeg-9.2.0...
Downloading: pvt.cppan.demo.mgk25.jbig.ar-2.1.0...
Downloading: pvt.cppan.demo.gif-5.1.4...
Downloading: pvt.cppan.demo.openjpeg.openjp2-2.3.0...
Downloading: pvt.cppan.demo.png-1.6.34...
Downloading: pvt.cppan.demo.tiff-4.0.9...
Downloading: pvt.cppan.demo.webp-0.6.1...
Downloading: pvt.cppan.demo.mgk25.jbig.jbig-2.1.0...
Downloading: pvt.cppan.demo.madler.zlib-1.2.11...
Local db data caused issues, trying remote one
Requesting dependency list...
Retrying...
Retrying...
Could not connect to server
curl error: Couldn't resolve proxy name
Downloading: pvt.cppan.demo.danbloomberg.leptonica-master...
Downloading: pvt.cppan.demo.png-1.6.34...
Downloading: pvt.cppan.demo.gif-5.1.4...
Downloading: pvt.cppan.demo.jpeg-9.2.0...
Downloading: pvt.cppan.demo.tiff-4.0.9...
Downloading: pvt.cppan.demo.mgk25.jbig.ar-2.1.0...
Downloading: pvt.cppan.demo.openjpeg.openjp2-2.3.0...
Downloading: pvt.cppan.demo.mgk25.jbig.jbig-2.1.0...
Downloading: pvt.cppan.demo.webp-0.6.1...
Downloading: pvt.cppan.demo.madler.zlib-1.2.11...
Downloading: pvt.cppan.demo.xz_utils.lzma-5.2.3...
Local db data caused issues, trying remote one
Requesting dependency list...
Retrying...
Retrying...
Could not connect to server
curl error: Couldn't resolve proxy name

**Comment by egorpugin** [comment]
Do you have a proxy? Maybe the issue's somehow related to it?

**Comment by hoangtocdo90** [comment]
some things happen with my computer.  i found this in VPN settings

127.0.0.1:8080
but every things works except cppan.
thanks for reply
