### ISSUE TITLE
[Question] how to add local lib and dll to cppan build ?

### ISSUE THREAD

**Issue by hoangtocdo90** [cppan/cppan#42]
Hi guys!
I'm using cppan but i don't want to build opencv and boost. I want to download and put it manualy
here is my cppan.yml
`    builds:
        
        vs2015_64:
            generator: Visual Studio 14 2015 Win64
    storage_dir: CPPAN_CACHE

        options:
            any:
                definitions:
                    public:
                      - UNICODE
                link_libraries:
                    public:
                      - opencv_world320
                link_directories:
                      - ./library/lib
                      - ./boost_1_66_0/lib64-msvc-14.0
`
But in my project additional library directories was :
E:/TesseractOpenCV/Boost/CPPAN_CACHE/obj/b1/58/3413/./library/lib
What's correct way to add local library to cppan build ?
Thanks!

**Comment by egorpugin** [comment]
Try this:
```
link_directories:
    - ${SDIR}/library/lib
    - ${SDIR}/boost_1_66_0/lib64-msvc-14.0
```
