### ISSUE TITLE
Windows 10 defender argue cppan.exe is a threat ?!

### ISSUE THREAD

**Issue by ABSoftAsia** [cppan/cppan#44]
Hi,

I download latest version (https://cppan.org/client/cppan-master-Windows-client.zip) of client in Windows, but defender shows this:
....
Alert level:Severe
Category:Trojan
Details:This program is dangerous and executes commands from an attacker.
....
I double checked the md5 hash is the same as official provided.
What's happen, is this right or wrong?

**Comment by egorpugin** [comment]
Yes, I also saw this. VirusTotal show zero treats.
I'm not sure how to fix this at the moment. Maybe contact MS.
Could you check file properties (detail tab), please?
Must be something likie this
![image](https://user-images.githubusercontent.com/4325333/37281890-9850a61c-2603-11e8-8edf-06d9adc98ec0.png)

**Comment by egorpugin** [comment]
See https://www.virustotal.com/#/file-analysis/NWUyZTlkN2QzNmQ3YjI3YWIxZDJjZWU3NTA0NGU3ZTA6MTUyMDg1NTA4Nw==

**Comment by egorpugin** [comment]
Can you try to update defender database?
On the latest updates nothing is detected.

**Comment by ABSoftAsia** [comment]
Yes, after defender updated, detects no threads.
Thanks !!
