### ISSUE TITLE
pvt.cppan.demo.danbloomberg.leptonica-1.74.4.dll

### ISSUE THREAD

**Issue by ASShusharin** [cppan/cppan#49]
Hello Egor. I'm trying to build a Tesseract 4 with OpenCV. I assembled a new version of OpenCV based on this instruction: http://answers.opencv.org/question/171470/opencv-ocrtesseractcreate-v305/?answer=171659#post-id-171659 (previously I assembled successfully Tesseract 3.05 and OpenCV in the Visual Studio project using this instruction). This time for Tesseract 4 and OpenCV I also assembled successfully. I wrote new paths to the project and the project was compiled successfully, but when I tried to ran it, I got this error:

![image](https://user-images.githubusercontent.com/8286479/39373866-68420f50-4a62-11e8-9309-0507cce949dc.png)

I want to note that when assembling Tesseract 4 in CMake it was not possible to register a path to Leptonica 1.74 or 1.75, so I realized that cppan automatically loads Leptonica 1.75 to Tesseract 4.

![image](https://user-images.githubusercontent.com/8286479/39374579-bf7ad5d4-4a64-11e8-9db1-8ae8c34d1af1.png)

**Comment by egorpugin** [comment]
It is also possible, that you have that buggy unstable cppan client from me.
Try to download from site as you have now latin user folder or try another unstable client from this post:




[cppan.zip](https://github.com/cppan/cppan/files/1956986/cppan.zip)

**Comment by ASShusharin** [comment]
Hi Egor, I tried to run tesseract 4 on test image and it recognized image. Can we consider that cppan compiled well?

![image](https://user-images.githubusercontent.com/8286479/39392982-0cfe6b6c-4ad9-11e8-9faa-3e0415d9143e.png)

Do you have any instructions how to build opencv+tess using cppan like your example (https://cppan.org/pvt.cppan.demo.intel.opencv.contrib.text/version/3.4.1)?

**Comment by ASShusharin** [comment]
I tried to build webcam_demo:
git clone https://github.com/cppan/webcam_demo 
cd webcam_demo
cppan --build webcam_demo.cpp
bin\webcam_demo

There are some errors:

![image](https://user-images.githubusercontent.com/8286479/39393926-7f68ae14-4ae4-11e8-9ac1-341926198416.png)

**Comment by egorpugin** [comment]
> Can we consider that cppan compiled well?

Yes.

> Do you have any instructions how to build opencv+tess using cppan for your example?

See https://github.com/cppan/cppan/issues/49#issuecomment-385033011

> webcam example

I've fixed it. Try it now.
`cppan --build webcam_demo.cpp -s`
If you see any errors - try it on the latest VS2017 - VS15.6.7.

**Comment by ASShusharin** [comment]
I compiled and run webcam_demo project successfully. 

![image](https://user-images.githubusercontent.com/8286479/39396373-769cf99e-4b06-11e8-84bd-3593bf9d81a7.png)

How can I use it for my project? What dependencies will I need to register?

**Comment by egorpugin** [comment]
See https://github.com/cppan/cppan/issues/49#issuecomment-385033011

**Comment by ASShusharin** [comment]
Ok, but if I use Visual Studio to build my project without cmake?

**Comment by egorpugin** [comment]
Then you have nothing to do at the moment.

**Comment by ASShusharin** [comment]
Can I use somehow dll like pvt.cppan.demo.intel.opencv.contrib.text-3.4.1.dll in my VS project?

**Comment by egorpugin** [comment]
> When I try to run my project in VS, I have an error linking to Leptonica 1.74.

Find that lep dll and put near tess dll.

> In the description of the module's is written that only Tesseract 3 versions are supported:

3 or later - v4 works fine - webcam demo confirms that.

> Can I use somehow dll like pvt.cppan.demo.intel.opencv.contrib.text-3.4.1.dll in my VS project?

This is not related to cppan. You can try to search on web how to include 3rd party libs into vs solutions.
At the moment cppan is cmake-oriented.

**Comment by ASShusharin** [comment]
What development environment do you use for Windows with CMake?

**Comment by egorpugin** [comment]
The latest VS2017, win10.
