### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by Telokis** [cppan/cppan#5]
[Cppan CI on Travis](https://travis-ci.org/cppan/cppan) show that the last build failed.
It would be nice to fix this so that each build is properly tested.
I'll probably be able to work on this issue (as well as #4) during this week end.
I'd be glad to do it and submit a pull request for each of those.

**Comment by egorpugin** [comment]
Fixed, see https://travis-ci.org/cppan/cppan/builds
