### ISSUE TITLE
Better names for libraries

### ISSUE THREAD

**Issue by zdenop** [cppan/cppan#51]
I am satisfied user of cppan, but naming convention drives me crazy:

1. They are too long ;-) (pvt.cppan.demo.gnome.pango.pango-1.42.1.dll or pvt.cppan.demo.danbloomberg.leptonica-1.75.3.dll is it really needed???)
2. Why demo substring in name? Is not finished yet? Or not full featured library?

I would prefer significantly shorter name convention. Some like project.libname-version.dll (e.g.  cppan.pango-1.42.1.dll, cppan.leptonica-1.75.3.dll)

**Comment by egorpugin** [comment]
1. It's similar to java packages.
domain.user.package.name

It's very unlikely that this will be changed.

2. demo means it's my manually added library.
If original authors register on the website and add this library themselves, name will be shorter, e.g. `pvt.danbloomberg.leptonica` and dll `pvt.danbloomberg.leptonica-1.75.3.dll`.

---

Currently only possible and partial workaround is to use `short_local_names: true` in `cppan.yml` config.
https://github.com/tesseract-ocr/tesseract/blob/master/cppan.yml#L3
But this is not tested properly yet.

---

Main work is ongoing on the cppan2 at the moment (it's not public yet). So, I'm doing mostly stability fixes here.
