### ISSUE TITLE
"tesseract_example" errors

### ISSUE THREAD

**Issue by ASShusharin** [cppan/cppan#52]
Hello Egor.  I updated Visual Studio to 2017 version and tried to compile the project: "tesseract_example". There were some errors. 

![image](https://user-images.githubusercontent.com/8286479/39661676-17ae59e6-506f-11e8-9fa3-92c362078dc6.png)

What could be cause of the errors?
I also tried to build "with_cppan", it works.

**Comment by egorpugin** [comment]
Don't know about VS errors. It's not the best place to ask about it.
Try to build in console `cmake --build .`. Works for me.
