### ISSUE TITLE
When I try to install some library using cppan, it says

### ISSUE THREAD

**Issue by datengx** [cppan/cppan#54]
C:\Users\Da\.cppan\storage\src\38\cb\0305\src\ccmain\equationdetect.cpp(235): error C3688: invalid literal suffix '锟?; literal operator or literal operator template 'operator ""锟? not found [C:\Users\Da\.cppan\storage\obj\38\cb\0305\build\7205c7b9\cppan\38cb0305\38cb0305.vcxproj] [C:\Users\Da\.cppan\storage\obj\42\9e\ba91\build\7205c7b9\cppan\429eba91\429eba91-b-d.vcxproj] [C:\Users\Da\.cppan\storage\tmp\build\7a6e40d4\7205c7b9\build\.cppan\cppan-d-b-d.vcxproj]

Any idea?

**Comment by egorpugin** [comment]
Are you using the latest VS (15.7.2) and cmake (3.11.1)?

**Comment by softrml** [comment]
Same error with VS(15.9.4) and cmake(3.13.2). Must be VS(15.7.2) and cmake(3.11.1)?
Is it something about character encoding because there is a Chinese character "锟" there?

**Comment by egorpugin** [comment]
Do you have Chinese user name?
