### ISSUE TITLE
Package 'pvt.cppan.demo.danbloomberg.leptonica' not found.

### ISSUE THREAD

**Issue by strName** [cppan/cppan#56]
**Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\30367> cd C:\Users\30367\tesseract
PS C:\Users\30367\tesseract> cppan
Cannot get dependencies from local database: Package 'pvt.cppan.demo.danbloomberg.leptonica' not found.
Requesting dependency list...
Retrying...
Retrying...
Could not connect to server
curl error: Failure when receiving data from the peer

PS C:\Users\30367\tesseract>**

**Comment by egorpugin** [comment]
Seems like you have issues when connecting to cppan.org.
Do you use proxy?

**Comment by strName** [comment]
Yes I have.

**Comment by egorpugin** [comment]
If you have login, you must specify it in `c:\users\your name\.cppan\cppan.yml`:
`
proxy:
  host: 192.168.191.129:3128
  user: proxy_test:123456
`

**Comment by strName** [comment]
it's worked! thks
