### ISSUE TITLE
Consider using more descriptive names for package folders

### ISSUE THREAD

**Issue by biocomp** [cppan/cppan#59]
Obviously, not a major issue, but nice to have.

Folders where packages are located are just sets of random symbols. So when build is running, it's not clear what's going on. Consider appending package names to some part of the path.

Instead of this:
`Done Building Project "C:\Users\UserName\.cppan\storage\obj\73\de\e32d\build\6f62728c\ALL_BUILD.vcxproj`

it's be nice to see something like this:
`Done Building Project "C:\Users\UserName\.cppan\storage\obj\73\de\boost.filesystem.e32d\build\6f62728c\ALL_BUILD.vcxproj`

**Comment by egorpugin** [comment]
You should take a look at `storage/lnk` dir with human readable links.

---

How to handle long names?
I tried or considered:
```
storage/pvt.cppan.demo.google...../ - exceeds 256
storage/pvt/cppan/demo/google - fine (win requires long paths enabled), but there will be a lot of subdirs (more than 256)
storage/sp/li/tt/ed/hash - cppan1/sw choice
```

**Comment by biocomp** [comment]
Oh, I see. Yeah, name length could be a problem. And you likely have more experience with this issue.
I won't have a good solution for you either. Although 256 limit seems a bit low.

Also, paths inside the package - I guess you don't control them? Then probably trimming package name only doesn't save many characters?

**Comment by egorpugin** [comment]
> Then probably trimming package name only doesn't save many characters?

Trimming where?
Once I saw very long path/file name in the package. That is another reason for short hashed names.
```
some user prefix/our part/some package file prefix
```
So the intent to gave more to left and right block and take as less as possible ourselves.

**Comment by biocomp** [comment]
I see. If this helps with long paths, I guess it's  not worth spending time on. Thanks! )
