### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by kxjhcs** [cppan/cppan#6]
cppan-master-win32-client run in my windows, error: 
The application was unable to start correctly (0xc000007b). Click OK to close

**Comment by egorpugin** [comment]
Do you have vs2015 redist installed? or visual studio 2015?

**Comment by egorpugin** [comment]
I've updated windows binaries.
Please try to re-download them and run again to check if error still exists.

**Comment by kxjhcs** [comment]
I'm sorry to bother you, when i install  vs2015 redist, it is runing ok.
tks
