### ISSUE TITLE
Syntax error in version.rc

### ISSUE THREAD

**Issue by zumm** [cppan/cppan#62]
Hi. I got a few errors from windres.exe about syntax error in version.rc during build tesseract-orc with mingw. Problem in lines like that:
> VALUE "FileDescription", PACKAGE_NAME_LAST " - 7739c757 - " PACKAGE_BUILD_CONFIG

I had to comment them to finish build.

I guess reason of this bug is here:
https://github.com/cppan/cppan/blob/v1/src/inserts/version.rc.in#L10
https://github.com/cppan/cppan/blob/v1/src/inserts/branch.rc.in#L10

May be need replace it with somthing like that:
> VALUE "FileDescription", "@PACKAGE_NAME_LAST@ - @config@ - @PACKAGE_BUILD_CONFIG@"

Unfortunetly, i can't build cppan to test it.

**Comment by egorpugin** [comment]
Hi. How do you run tesseract build?

**Comment by zumm** [comment]
I use MinGW64 + CMake +CLion. I did build from CLion with CMakeLists.txt containing something like that:
```
set(DEPENDENCIES
    pvt.cppan.demo.google.tesseract.libtesseract
    pvt.cppan.demo.danbloomberg.leptonica
)

find_package(CPPAN REQUIRED)
cppan_add_package(${DEPENDENCIES})
cppan_execute()

add_executable(${PROJECT_NAME} ${HEADER_FILES} ${SOURCE_FILES})
target_link_libraries(${PROJECT_NAME} ${DEPENDENCIES})
```
Btw, i did fix this problem by modify version.rc.in and branch.rc.in patterns in cppan executable.

**Comment by egorpugin** [comment]
Those defs (PACKAGE_NAME_LAST, PACKAGE_BUILD_CONFIG) must come from somewhere. Not sure why they are not provided in your case.
Anyways cppan is deprecated now, please follow sw development (https://github.com/SoftwareNetwork/sw).
I hope cmake support will come there soon too.

**Comment by egorpugin** [comment]
FYI: I've added initial cmake integration for sw.
(windows only at the moment)

To use it:
1. Download new binary
2. Run `sw setup` (requires administrator rights)
3. See example at https://github.com/SoftwareNetwork/sw/blob/master/test/integrations/CMakeLists.txt
