### ISSUE TITLE
Having two versions of Visual Studio installed-how to choose which to use

### ISSUE THREAD

**Issue by andreshur** [cppan/cppan#63]
I have Visual Studio 2017 and VS 2008 installed on the same computer.
When trying to compile Tesseract 4.0.0 by:
cppan --build pvt.cppan.demo.google.tesseract.libtesseract-master
...it chooses VS 2008 as a compiler.
How could I force or tell cppan which one to use ? It seems to be detecting automatically VS 2008, which is incompatible with that Tesseract version.

Here are some log lines:

`Requesting dependency list...`
`Reading package specs...`
`--`
`-- Performing test run`
`--`
`Generating build files...`
`-- Building for: Visual Studio 9 2008`
`-- The C compiler identification is MSVC 15.0.30729.1`
`-- The CXX compiler identification is MSVC 15.0.30729.1`
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe`
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe`
`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: C:/Users/Andres/AppData/Local/Temp/cppan/temp/1151-81a1-79d5-79fb/build`
`Generating build files...`
`-- Building for: Visual Studio 9 2008`
`-- Check if the system is big endian`
`-- Searching 16 bit integer`
`-- Looking for sys/types.h`
`-- Looking for sys/types.h - found`
`-- Looking for stdint.h`
`-- Looking for stdint.h - not found`
`-- Looking for stddef.h`
`-- Looking for stddef.h - found`

**Comment by egorpugin** [comment]
Try to pass generator option to cmake like this:

```
cppan --build pvt.cppan.demo.google.tesseract.libtesseract-master -- -G "Visual Studio 15 2017"
```

---

Second option is to create `cppan.yml` in current dir and make some `local_settings` there like here https://github.com/tesseract-ocr/tesseract/blob/master/cppan.yml#L11

---

And the last option is to use SW. SW is cppan v2 https://github.com/SoftwareNetwork/sw

**Comment by egorpugin** [comment]
Please, proceed to sw https://github.com/SoftwareNetwork/sw
