### ISSUE TITLE
TesseractConfig.cmake  could not find load file: cppan.cmake

### ISSUE THREAD

**Issue by CDanU** [cppan/cppan#7]
Following the tesseract 3.05 build guide  ( only difference is that I configured it to be non static x64 ) I successfully compiled tesseract but upon trying to find the package with cmake I get these errors: 

```
CMake Error at ..../tesseract/build/TesseractTargets.cmake:1 (include):
  include could not find load file:

    .../tesseract/build/cppan.cmake
Call Stack (most recent call first):
  .../tesseract/build/TesseractConfig.cmake:22 (include)
  CMakeLists.txt:6 (find_package)
```

This error happens because TesseractTargets.cmake is trying to find cppan.cmake in '.../tesseract/build/cppan.cmake' but it is located in '.../tesseract/build/**exports**/cppan.cmake' 
Changing the path to '.../tesseract/build/**exports**/cppan.cmake' in TesseractTargets.cmake I get this error: 

```
CMake Error at CMakeLists.txt:6 (find_package):
  Found package configuration file:

    .../tesseract/build/TesseractConfig.cmake

  but it set Tesseract_FOUND to FALSE so package "Tesseract" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  cppan-helpers
```
The cppan-helpers are also located in .../tesseract/build/**exports**/

Here is a complete list of all files, if that helps: [list](https://gist.github.com/CDanU/4774356ddec5ff96c62c608f602321b6)

**Comment by egorpugin** [comment]
Hi,

It seems wiki page in tess repo is a bit confusing. I've fixed it.
Looks like your are trying to include tess to **your application** and not to build tesseract for development.
In this case you should take a look at example project https://github.com/cppan/tesseract_example
And if you are using cmake, more precisely at https://github.com/cppan/tesseract_example/tree/master/with_cmake

Hope this helps.

ps.
In your description you're mixing different approaches, so it won't work in any case.

**Comment by CDanU** [comment]
Yes, you are right, I totally did miss that one important part in the wiki. CMake now generates everything as it should, thanks.
