### ISSUE TITLE
After upgrade to SDL 2.0.5, Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by dimi309** [cppan/cppan#8]
Good afternoon,

I've noticed that the new version of SDL, 2.0.5, is now available on cppan. I have tried to rebuild a [demo](https://github.com/dimi309/small3d-cppan-example) linking to my library, [small3d](https://cppan.org/pvt.coding3d.small3d), without changing anything. But I get the following error:

```
Undefined symbols for architecture x86_64:
  "_COREAUDIO_bootstrap", referenced from:
      _bootstrap in libpvt.cppan.demo.valve.sdl.sdl-2.0.5.a(SDL_audio.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/main] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2
```
In case this is due to the SDL upgrade, I have tried to build explicitly using the 2.0.4 version, by changing 

`pvt.cppan.demo.valve.sdl.sdlmain: 2`

to 

`pvt.cppan.demo.valve.sdl.sdlmain: 2.0.4`

in the comments of the demo's [main.cpp](https://github.com/dimi309/small3d-cppan-example/blob/master/avoidTheBug/main.cpp), but it doesn't seem to work. It still tries to use version 2.0.5

Do you think there is something else I could try?

Thanks!

**Comment by egorpugin** [comment]
No matter what in main, your library uses 2.*.* version, so it takes 2.0.5.
Regarding this error, I should check building of sdl 2.0.5 on linux/mac.
I've added it from 2.0.4 template. Obviously something is broken now.

**Comment by egorpugin** [comment]
At the moment you can reupload your project with settings sdl version to 2.0.4 explicitly.

**Comment by dimi309** [comment]
Good, that worked! There's two things I've noticed by the way. They are not too serious, but I am mentioning them, in case it helps:

- When I add a new version of a package on the cppan web interface, sometimes I have to do it twice. Either it does not work the first time for some unknown reason, or it is because I need to press tab in the last textbox in which I add information (the git tag field in my case), otherwise the information doesn't go through. Either way, there is no error message. The version just does not get added.

- When I build something with cppan --build, if I then delete the executable and build again, with no error or anything being reported, there is no executable produced in the directory in which I am building. It looks like this has to do with cppan detecting that there are no changes in the source code, because if I do change something in one of the source code files and build again, the executable reappears.

I am not opening an issue for these things, because I am not sure if they are serious enough for that, but I still though to let you know.

**Comment by egorpugin** [comment]
Hmm...
1) Probably I should add a message (in notifications) that package adding in the process right now. You may think that you need to do it twice because the process is not so fast.
2) What is your system? Linux? macOS? I'll investigate. On windows executable is produced every time.

**Comment by dimi309** [comment]
1) Maybe that's it and, indeed a message would help the website look more robust.
2) I've observed this behaviour on MacOS.

**Comment by egorpugin** [comment]
Ok, I've fixed 1).
Will look at 2) tomorrow.

**Comment by dimi309** [comment]
Great!

**Comment by egorpugin** [comment]
Confirmed 2). But I'm now preparing first 0.2.x (0.2.0 obviously) release and it in some sense changes are related to code with this issue. I'll try fix it at once.
Probably 2-3 days. You should see a notification on the client when new version is available.

**Comment by dimi309** [comment]
I run the upgrade every day I'm using it anyway :)

**Comment by egorpugin** [comment]
Glad to hear. :)
By the way, I saw you're using conan too.
Maybe you could share some thoughts what is better in it than in cppan?
I'd like to compare both apps and maybe add more functionality to cppan based on your feedback. 
(The biggest difference is probably binary builds or packages but Im planning them too.)

**Comment by dimi309** [comment]
As much as time allows, I use everything that is available to me :) I'm not sure I could make a comparison... Both tools work well and, frankly, since the libraries get cached with cppan after being compiled once, I don't think it's urgent to have prebuilt packages... The thing is though, I use both conan and cppan as a package "provider" let's say. Someone who constantly consumes different packages for his or her work might be better suited to answer that question...

**Comment by egorpugin** [comment]
Got it, thanks!

**Comment by egorpugin** [comment]
> Confirmed 2). But I'm now preparing first 0.2.x (0.2.0 obviously) release and it in some sense contains changes related to code with this issue. I'll try fix it at once.
Probably 2-3 days. You should see a notification on the client when new version is available.

Okay... :(

@dimi309 Hey there!
Sorry, it took so long, I worked hard on 0.2.0 version.
I've fixed sdl 2.0.5. It should be available right now.
Also it seems there's an autofix for copying output binaries on linux/os x. I'll upload the new client in a day or two. Have to do some last checks and slightly change download procedure.

**Comment by egorpugin** [comment]
Ok, 0.2.0 is out. Feel free to try it, report any bugs etc. :)

**Comment by dimi309** [comment]
Looks good! Thanks!
