### ISSUE TITLE
'db.version' does not exist

### ISSUE THREAD

**Issue by ilovin** [cppan/cppan#9]
system: windows 10 x64
redist 2015: 14.0.24215(both x64 and x86)
I download the cppan.exe to D:\software and add it to path
but when I use cppan I get:

> Cannot get dependencies from local database: File 'C:/Users\name\.cppan\storage\etc\database\repository\db.version' does not exist
Trying origin remote
Requesting dependency list... Ok
Some packages (1) are unresolved

**Comment by egorpugin** [comment]
Could you please try to run the same command but with `--verbose` or `--trace` option? And attach logs here.

**Comment by ilovin** [comment]
- after running `--verbose` I get log_verbose.txt
- after running `--trace` I get log_trace.txt

[log_trace.txt](https://github.com/cppan/cppan/files/672544/log_trace.txt)
[log_verbose.txt](https://github.com/cppan/cppan/files/672546/log_verbose.txt)

**Comment by egorpugin** [comment]
Please, remove `C:/Users\name\.cppan\storage\` dir and re-run your command with `--trace` option.

**Comment by egorpugin** [comment]
And attach log here.

**Comment by egorpugin** [comment]
I've updated the client. Try `cppan --self-upgrade` and then run your usual command.

**Comment by ilovin** [comment]
after removing the `storage` folder and upgrade the client,
the `db.version` error disappear.
re-run `cppan --trace`, the log is as follows
[trace.txt](https://github.com/cppan/cppan/files/673534/trace.txt)

**Comment by egorpugin** [comment]
Should be fixed now.

**Comment by ilovin** [comment]
problem solved, thanks a lot
